C42G02Demo.PL/Controllers/EmployeeController.cs
using AutoMapper;
using C42G02Demo.BLL.Interfacies;
using C42G02Demo.DAL.Model;
using C42G02Demo.PL.Helpers;
using C42G02Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace C42G02Demo.PL.Controllers
{
	[Authorize]
	public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _env;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork,
                                  IWebHostEnvironment env,
                                  IMapper mapper) //Ask CLR To Create Object Of EmployeeRepository
        {
            _unitOfWork = unitOfWork;
            _env = env;
            _mapper = mapper;
        }
        public  async Task<IActionResult> Index(string SearchValue)
        {
            IEnumerable<Employee> employees;
            
            if (string.IsNullOrEmpty(SearchValue))
                 employees =  await _unitOfWork.EmployeeRepository.GetAllAsync();
            else
                employees = _unitOfWork.EmployeeRepository.GetEmployeesByName(SearchValue);

            var mappedEmployees = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);
            return View(mappedEmployees);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Departments = await _unitOfWork.DepartmentRepository.GetAllAsync(); // Populate the ViewBag
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            if (ModelState.IsValid)
            {
                #region Manual Mapping
                /// Manual Mapping
                //var mappedEmployee = new Employee
                //{
                //    Name = employeeVM.Name,
                //    age = employeeVM.age,
                //    Address = employeeVM.Address,
                //    IsActive = employeeVM.IsActive,
                //    Email = employeeVM.Email,
                //    HireDate = employeeVM.HireDate,
                //    PhoneNumber = employeeVM.PhoneNumber,
                //    Salary = employeeVM.Salary,
                //    Id = employeeVM.Id,
                //    Department = employeeVM.Department,
                //    DepartmentId = employeeVM.DepartmentId
                //}; 
                #endregion

                employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "Images");

                var mappedEmployee = _mapper.Map<EmployeeViewModel,Employee>(employeeVM);

                await _unitOfWork.EmployeeRepository.AddAsync(mappedEmployee);

                await _unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employeeVM);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id, string viewName = "Details")
        {
            if (!id.HasValue)
                return BadRequest();

            var employees = await _unitOfWork.EmployeeRepository.GetByIdAsync(id.Value);

            if (employees == null)
                return NotFound();

            var mappedEmployee = _mapper.Map<Employee, EmployeeViewModel>(employees);

            return View(viewName, mappedEmployee);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue)
                return BadRequest();

            var employees = await _unitOfWork.EmployeeRepository.GetByIdAsync(id.Value);
            if (employees== null)
                return NotFound();
            
            var mappedEmployee = _mapper.Map<Employee, EmployeeViewModel>(employees);
            
            ViewBag.Departments = await _unitOfWork.DepartmentRepository.GetAllAsync(); // Populate the ViewBag
            return View(mappedEmployee);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int? id, EmployeeViewModel employeeVM)
        {
            if (id != employeeVM.Id)
                return BadRequest();

            if (!ModelState.IsValid)
            {
                return View(employeeVM);
            }
                
            try
            {
                if(employeeVM.Image is not null)
                    employeeVM.ImageName = DocumentSettings.UploadFile(employeeVM.Image, "Images");

                var mappedEmployees = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                
                _unitOfWork.EmployeeRepository.Update(mappedEmployees);
                await _unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                // 2. Friendly Msg

                if (_env.IsDevelopment())
                    ModelState.AddModelError(string.Empty, ex.Message);
                else
                    ModelState.AddModelError(string.Empty, "An Error Occured During Update Employee Operation");

                return View(employeeVM);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(EmployeeViewModel employeeVM)
        {
            try
            {
                var mappedEmployee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                
                _unitOfWork.EmployeeRepository.Delete(mappedEmployee);
                
                var res = await _unitOfWork.CompleteAsync();
                
                if (res > 0)
                    DocumentSettings.DeleteFile(employeeVM.ImageName, "Images");
                
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                // 2. Friendly Msg

                if (_env.IsDevelopment())
                    ModelState.AddModelError(string.Empty, ex.Message);
                else
                    ModelState.AddModelError(string.Empty, "An Error Occured During Update Employee Operation");

                return View(employeeVM);
            }
        }
    }
}

C42G02Demo.PL/Controllers/RoleController.cs
using AutoMapper;
using C42G02Demo.DAL.Model;
using C42G02Demo.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace C42G02Demo.PL.Controllers
{
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IMapper _mapper;

        public RoleController(RoleManager<IdentityRole> roleManager , IMapper mapper)
        {
            _roleManager = roleManager;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            {
                var Roles = await _roleManager.Roles.ToListAsync();

                var mappedRoles = _mapper.Map<IEnumerable<IdentityRole>, IEnumerable<RoleViewModel>>(Roles);

                return View(mappedRoles);
            }
            else
            {
                var Role = await _roleManager.FindByNameAsync(SearchValue);

                var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(Role);

                return View(new List<RoleViewModel> { mappedRole });
            }
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var mappedRole = _mapper.Map<RoleViewModel,IdentityRole>(model);

                await _roleManager.CreateAsync(mappedRole);

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            if (id is null)
                return BadRequest();

            var Role = await _roleManager.FindByIdAsync(id);

            if (Role is null)
                return NotFound();

            var mappedRole = _mapper.Map<IdentityRole, RoleViewModel>(Role);

            return View(viewName, mappedRole);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel model)
        {
            if (id != model.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                try
                {
                    var Role = await _roleManager.FindByIdAsync(model.Id);

                    Role.Name = model.RoleName;

                    await _roleManager.UpdateAsync(Role);

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete(string id)
        {
            try
            {
                var Role = await _roleManager.FindByIdAsync(id);

                await _roleManager.DeleteAsync(Role);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

                return RedirectToAction("Error", "Home");
            }
        }
    }
}

C42G02Demo.PL/Controllers/UserController.cs
using AutoMapper;
using C42G02Demo.DAL.Model;
using C42G02Demo.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace C42G02Demo.PL.Controllers
{
	public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;

        public UserController(UserManager<ApplicationUser> userManager , 
							 IMapper mapper)
        {
			_userManager = userManager;
            _mapper = mapper;
        }

		public async Task<IActionResult> Index(string SearchValue)
		{
			if (string.IsNullOrEmpty(SearchValue))
			{
				var Users = await _userManager.Users.Select(
					U => new UserViewModel()
					{
						Id = U.Id,
						FName = U.FName,
						LName = U.LName,
						Email = U.Email,
						PhoneNumber = U.PhoneNumber,
						Roles = _userManager.GetRolesAsync(U).Result
					}).ToListAsync();
				return View(Users);
			}
			else
			{
				var User = await _userManager.FindByEmailAsync(SearchValue);

				var MappedUser = new UserViewModel()
				{
					Id = User.Id,
					FName = User.FName,
					LName = User.LName,
					Email = User.Email,
					PhoneNumber = User.PhoneNumber,
					Roles = _userManager.GetRolesAsync(User).Result
				};
				return View(new List<UserViewModel> { MappedUser });
			}
		}

		[HttpGet]
		public async Task<IActionResult> Details(string id , string viewName = "Details")
		{
			if(id is null)
				return BadRequest();

			var user = await _userManager.FindByIdAsync(id);

			if(user is null)
				return NotFound();

			var mappedUser = _mapper.Map<ApplicationUser, UserViewModel>(user);

			return View(viewName, mappedUser);
		}

		[HttpGet]
		public async Task<IActionResult> Edit(string id)
		{
			return await Details(id, "Edit");
        }

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel model)
		{
			if (id != model.Id)
				return BadRequest();

			if (ModelState.IsValid)
			{
				try
				{
                    var User = await _userManager.FindByIdAsync(model.Id);
					
					User.PhoneNumber = model.PhoneNumber;
					User.FName = model.FName;
					User.LName = model.LName;

                    await _userManager.UpdateAsync(User);

                    return RedirectToAction(nameof(Index));
				}
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
			
			return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> Delete(string id) 
		{
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDelete([FromRoute] string id)
		{
            try
            {
				var User = await _userManager.FindByIdAsync(id);
					
				await _userManager.DeleteAsync(User);

				return RedirectToAction(nameof(Index));
			}
			catch (Exception ex)
			{
                ModelState.AddModelError(string.Empty, ex.Message);

				return RedirectToAction("Error", "Home");
            }

		}
    }
}

C42G02Demo.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->

	<link href="~/css/authstylesheet.css" rel="stylesheet" />

</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		
		@RenderBody()

		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	@await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

C42G02Demo.PL/Views/Shared/_ButtonsPartial.cshtml
@model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-info">
        <i class="fa fa-eye" aria-hidden="true"></i> @* Details *@
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fa fa-pencil-square" aria-hidden="true"></i> @* Update *@
    </a>
</td>

<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fa fa-trash" aria-hidden="true"></i> @* Delete *@
    </a>
</td>

C42G02Demo.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - C42G02Demo.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">C42G02Demo.PL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - C42G02Demo.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>